name: Publish to ShotGrid

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish cpenv module to ShotGrid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish cpenv module
        uses: cpenv/github-actions-publish@v2
        with:
          module_root: "."
          repo_name: bns_shotgun
          repo_type: shotgun
          repo_shotgrid_base_url: ${{ secrets.SHOTGRID_BASE_URL }}
          repo_shotgrid_script_name: ${{ secrets.SHOTGRID_SCRIPT_NAME }}
          repo_shotgrid_api_key: ${{ secrets.SHOTGRID_API_KEY }}
          repo_shotgrid_module_entity: CustomNonProjectEntity01
          repo_overwrite: true
